/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

int main(void)
{
	// pointer variables to registers
	int *pClkCtrlRed = 0x40023830;
	int *pPortDModeReg = 0x40020C00;
	int *pPortDOutReg = 0x40020C14;

	temp = *pClkCtrlReg; //read operation
	temp = temp | 0x08; // Set the bits
	*pClkCtrlReg = temp; // write back

	// Configure the mode of the pin to output
	// first clear the bits 24 and 25
	*pClkCtrlReg &= 0xFCFFFFFF;
	// set 24 bit to 1
	*pClkCtrlReg |= 0x01000000;

	// configure the 12 bit of the output to 1
	*pPortDOutReg |= 0x1000;

	while(1);

}
